import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import { mdsvex } from 'mdsvex';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	extensions: ['.svelte', '.svx'],

	// Consult https://svelte.dev/docs/kit/integrations
	// for more information about preprocessors
	preprocess: [vitePreprocess(), mdsvex()],

	kit: {
		alias: {
			$locales: 'src/locales'
		},
		// adapter-auto only supports some environments, see https://svelte.dev/docs/kit/adapter-auto for a list.
		// If your environment is not supported, or you settled on a specific environment, switch out the adapter.
		// See https://svelte.dev/docs/kit/adapters for more information about adapters.
		adapter: adapter(),
		prerender: {
			handleUnseenRoutes: 'warn',
			entries: [
				'/',
				'/ethos',
				'/backend',
				'/backend/pocketbase',
				'/backend/postgres',
				'/cli',
				'/cli/installation',
				'/cli/environment-variables',
				'/create',
				'/dev',
				'/build',
				'/generate',
				'/generate/form',
				'/generate/resource',
				'/generate/schema',
				'/generate/scaffold',
				'/generate/ai',
				'/destroy',
				'/enable',
				'/enable/auth',
				'/enable/api',
				'/enable/api-keys',
				'/enable/s3',
				'/enable/smtp',
				'/enable/notifications',
				'/enable/teams',
				'/enable/payments',
				'/enable/subscriptions',
				'/enable/i18n',
				'/enable/cms',
				'/enable/workflow',
				'/enable/whatsapp',
				'/disable',
				'/i18n',
				'/i18n/extract',
				'/i18n/watch',
				'/i18n/status',
				'/i18n/clean',
				'/sync',
				'/test',
				'/test/unit',
				'/test/integration',
				'/seeds',
				'/seeds/save',
				'/seeds/load',
				'/seeds/clear',
				'/fixtures',
				'/fixtures/generate',
				'/fixtures/load',
				'/fixtures/clear',
				'/legal',
				'/legal/privacy',
				'/legal/terms',
				'/ui',
				'/ui/add',
				'/ui/base',
				'/routes',
				'/provision',
				'/deploy',
				'/serverless',
				'/serverless/vercel',
				'/serverless/netlify',
				'/serverless/cloudflare',
				'/static',
				'/account',
				'/account/signup',
				'/account/login',
				'/account/whoami',
				'/account/logout',
				'/helpers',
				'/helpers/pocketbase',
				'/helpers/postgres',
				'/helpers/github-action',
				'/es',
				'/es/ethos',
				'/es/backend',
				'/es/backend/pocketbase',
				'/es/backend/postgres',
				'/es/cli',
				'/es/cli/installation',
				'/es/cli/environment-variables',
				'/es/create',
				'/es/dev',
				'/es/build',
				'/es/generate',
				'/es/generate/form',
				'/es/generate/resource',
				'/es/generate/schema',
				'/es/generate/scaffold',
				'/es/generate/ai',
				'/es/destroy',
				'/es/enable',
				'/es/enable/auth',
				'/es/enable/api',
				'/es/enable/api-keys',
				'/es/enable/s3',
				'/es/enable/smtp',
				'/es/enable/notifications',
				'/es/enable/teams',
				'/es/enable/payments',
				'/es/enable/subscriptions',
				'/es/enable/i18n',
				'/es/enable/cms',
				'/es/enable/workflow',
				'/es/enable/whatsapp',
				'/es/disable',
				'/es/i18n',
				'/es/i18n/extract',
				'/es/i18n/watch',
				'/es/i18n/status',
				'/es/i18n/clean',
				'/es/sync',
				'/es/test',
				'/es/test/unit',
				'/es/test/integration',
				'/es/seeds',
				'/es/seeds/save',
				'/es/seeds/load',
				'/es/seeds/clear',
				'/es/fixtures',
				'/es/fixtures/generate',
				'/es/fixtures/load',
				'/es/fixtures/clear',
				'/es/legal',
				'/es/legal/privacy',
				'/es/legal/terms',
				'/es/ui',
				'/es/ui/add',
				'/es/ui/base',
				'/es/routes',
				'/es/provision',
				'/es/deploy',
				'/es/serverless',
				'/es/serverless/vercel',
				'/es/serverless/netlify',
				'/es/serverless/cloudflare',
				'/es/static',
				'/es/account',
				'/es/account/signup',
				'/es/account/login',
				'/es/account/whoami',
				'/es/account/logout',
				'/es/helpers',
				'/es/helpers/pocketbase',
				'/es/helpers/postgres',
				'/es/helpers/github-action'
			]
		}
	}
};

export default config;
